id: I60B54827
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:33:43+00:00'
last_modified: '2022-06-08T16:27:19.398238+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6615
  title: དམངས་ཁྲོད་གཏམ་དཔེ་ལེགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    07B7:
      image_group_id: I3CN6617
      title: ''
      total_pages: 1018
      order: 1
      base_file: 07B7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
